steps:
  - name: ":docker:"
    plugins:
      docker-compose#v1.3.2:
        build: app
        image-repository: "$DOCKER_IMAGE_REPO"
    agents:
      queue: "$BUILDER_QUEUE"
  
  - wait

  - name: ":rspec:"
    command: "scripts/ci/parallel_specs.sh"
    artifact_paths: "log/**/*"
    env:
      RAILS_ENV: test
    plugins:
      docker-compose#v1.3.2:
        run: app
    parallelism: 400
    agents:
      queue: "$RUNNER_QUEUE"